apiVersion: v1
kind: ConfigMap
metadata:
  name: app-one-html
data:
  index.html: |
    <html>
      <head>
        <title>App One</title>
      </head>
      <body>
        <h1>Welcome to App One</h1>
        <p>This is a simple web application running on Kubernetes.</p>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
        - name: app-one-container
          image: python:3.9-slim
          command: ["python", "-m", "http.server", "80"]
          workingDir: /app
          volumeMounts:
            - name: html-volume
              mountPath: /app
      volumes:
        - name: html-volume
          configMap:
            name: app-one-html

---
apiVersion: v1
kind: Service
metadata:
  name: app-one-service
spec:
  selector:
    app: app-one
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
