RAM = 512
CPUS = 1

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Dossier partagé via NFS (avec options compatibles)
  config.vm.synced_folder "./config", "/vagrant_shared",
                          type: "nfs",
                          mount_options: ['vers=4', 'tcp']

  config.vm.define "mutezaS" do |master|
    master.vm.hostname = "mutezaS"
    master.vm.network "private_network", ip: "192.168.56.110"

    master.vm.provider :libvirt do |lv|
      lv.memory = RAM
      lv.cpus = CPUS
    end

    # Installation de nfs-common avant le reste
    master.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y nfs-common
    SHELL

    master.vm.provision "shell", path: "./script/master.sh"
  end

  config.vm.define "hulefevrSW" do |worker|
    worker.vm.hostname = "hulefevrSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider :libvirt do |lv|
      lv.memory = RAM
      lv.cpus = CPUS
    end

    # Installation de nfs-common avant le script
    worker.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y nfs-common
    SHELL

    worker.vm.provision "shell", path: "./script/worker.sh", args: ["192.168.56.110"]
  end
end
