apiVersion: v1
kind: ConfigMap
metadata:
  name: app-three-html
data:
  index.html: |
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <title>App 3</title>
        <style>
          body {
            background-color: #d1ecf1;
            color: #0c5460;
            font-family: 'Segoe UI', sans-serif;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
          }
          h1 {
            color: #17a2b8;
            font-size: 3rem;
          }
          p {
            font-size: 1.2rem;
          }
        </style>
      </head>
      <body>
        <h1>Bienvenue sur App 3</h1>
        <p>Application par défaut</p>
      </body>
      </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-three-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-three
  template:
    metadata:
      labels:
        app: app-three
    spec:
      containers:
        - name: app-three-container
          image: python:3.9-slim
          command: ["python", "-m", "http.server", "80"]
          workingDir: /app
          volumeMounts:
            - name: html-volume
              mountPath: /app
      volumes:
        - name: html-volume
          configMap:
            name: app-three-html
---
apiVersion: v1
kind: Service
metadata:
  name: app-three-service
spec:
  selector:
    app: app-three
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
