apiVersion: v1
kind: ConfigMap
metadata:
  name: app-two-html
data:
  index.html: |
   <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <title>App 2</title>
      <style>
        body {
          background-color: #fff3cd;
          color: #856404;
          font-family: 'Segoe UI', sans-serif;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          height: 100vh;
        }
        h1 {
          color: #fd7e14;
          font-size: 3rem;
        }
        p {
          font-size: 1.2rem;
        }
      </style>
    </head>
    <body>
      <h1>Bienvenue sur App 2</h1>
      <p>Voici la deuxième application (avec 3 réplicas !)</p>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      containers:
        - name: app-two-container
          image: python:3.9-slim
          command: ["python", "-m", "http.server", "80"]
          workingDir: /app
          volumeMounts:
            - name: html-volume
              mountPath: /app
      volumes:
        - name: html-volume
          configMap:
            name: app-two-html
---
apiVersion: v1
kind: Service
metadata:
  name: app-two-service
spec:
  selector:
    app: app-two
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
